---
Name: security-layouts
After:
  - 'framework/*'
  - 'cms/*'
---

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Fractas\SecurityForm\SecurityFormController

# Fractas\SecurityForm\SecurityFormController:
#   company_logo: 'path/to/logo.svg' # path to project or company logo
#   company_name: 'ACME' # name of company or project
#   company_link: 'http://www.example.com' # project or company link
