---
Name: security-layouts
---

Page_Controller:
  extensions:
    - Fractas\SecurityForm\SecurityFormController

# Fractas\SecurityForm\SecurityFormController:
#   company_logo: 'path/to/logo.svg' # path to project or company logo
#   company_name: 'ACME' # name of company or project
#   company_link: 'http://www.example.com' # project or company link
